drivers: hwmon: eswin: fan-control: Resolve compilation error
Renamed pwm_apply_state() to pwm_apply_might_sleep()

When upgrading to 6.6.62, we get the below compilation error.
drivers/hwmon/eswin-fan-control.c:114:9: error: implicit declaration of function 'pwm_apply_state'; did you mean 'pwm_apply_args'? [-Werror=implicit-function-declaration]
  114 |         pwm_apply_state(ctl->pwm, &state);
      |         ^~~~~~~~~~~~~~~
      |         pwm_apply_args

This is because, from kernel 6.6.33 onwards, pwm_apply_state() is
renamed to pwm_apply_might_sleep()
Commit:
--------
a10c3d5ff9a343c0b898215253750fedc38ac765

Signed-off-by: Pritesh Patel <pritesh.patel@einfochips.com>